trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@4
  displayName: 'Build & Test (Maven)'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    options: '--batch-mode'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
